function data()
return {
	en = {

		["mod_name"] = "Level crossing signals",
		["mod_desc"] = "Signs for securing level crossings in rail traffic in the period from 1955 to the present day.",
        
        ["Bahnübergang Assets"] = "Level crossing signals",
        ["Bahnübergang Assets Desc"] = "Signs for securing level crossings in rail traffic",
        ["Österreich"] = "Acitvate Austrian signals?",
    
        ["BÜ0/BÜ1 Bauform 1955"] = "Level crossing signal 1955",
        ["BÜ0/BÜ1 Bauform 1960"] = "Level crossing signal 1960",
        ["BÜ0/BÜ1 Bauform 1975"] = "Level crossing signal 1975",
        ["BÜ0/BÜ1 Bauform 2000"] = "Level crossing signal 2000",
        ["BÜ Signal der ÖBB"] = "Level crossing signal ÖBB",     
        ["BÜ Signale Description"] = "ignal for securing level crossings. When the light is flashing, the level crossing is technically secured, otherwise the vehicle must stop and secure the level crossing manually.",
        ["links"] = " left",
        ["Type"] = "Type",
        ["Pfosten"] = "Post",
        ["Bü gelb KM"] = "Bü yellow KM",
        ["Bü weiß KM"] = "Bü white KM",
        ["Bü weiß"] = "Bü Bü",
        ["HET"] = "HET",
        ["autom. HET"] = "autom. HET",
        ["ET"] = "ET",
        ["autom. ET"] = "autom. ET",
        ["Wiederholer Pfosten"] = "Repeater post",
        ["Wiederholer Signal"] = "Repeater signal",
        ["P"] = "P",
        ["L"] = "L",
        ["Bü2 alt"] = "Bü2 old",
        ["Bü2 neu"] = "Bü2 new",
        ["Bü3"] = "Bü3",
        ["Pfeifpflocḱ"] = "Whistle peg (AT)",
        ["TrackPos"] = "Position on track",
        ["right"] = "right",
        ["left"] = "left",
        ["MastPos"] = "Position on pole",
        ["oben"] = "top",
        ["1 unterhalb"] = "1 below",
        ["2 unterhalb"] = "2 below",
        ["Pfosten"] = "Post",
        ["mit L"] = " with L sign",
        ["mit P"] = " with P sign",
        ["links"] = " left",
        ["Betonpfosten für BÜ Assets"] = "Concrete pole for rail crossing assets",
        ["für Assets"] = " (Assets can be added to this pole by choice)",
        ["Auslöser"] = "\nTriggers whistles from passing trains.",

        ["tooltip_type"] = "Variant",
        ["tooltip_trackpos"] = "Is the sign on the left or right of the track?",
        ["tooltip_mastpos"] = "If several signs are hanging on one pole, they can be moved downwards with this.",
        ["tooltip_autokm"] = "For inscribable signs, an automatic number can be generated (otherwise manually assigned as a name).",

	},
	de = {

		["mod_name"] = "Bahnübergangs-Signale",
		["mod_desc"] = "Schilder für die Sicherung von Bahnübergängen im Eisenbahnverkehr im Zeitraum von 1955 bis heute.",

        ["Bahnübergang Assets"] = "Bahnübergang Assets",
        ["Bahnübergang Assets Desc"] = "Schilder für die Sicherung von Bahnübergängen im Eisenbahnverkehr",
        ["Österreich"] = "Österreichische Signale aktivieren?",
    
        ["BÜ0/BÜ1 Bauform 1955"] = "BÜ-Signal Bauform 1955",
        ["BÜ0/BÜ1 Bauform 1960"] = "BÜ-Signal Bauform 1960",
        ["BÜ0/BÜ1 Bauform 1975"] = "BÜ-Signal Bauform 1975",
        ["BÜ0/BÜ1 Bauform 2000"] = "BÜ-Signal Bauform 2000",
        ["BÜ Signal der ÖBB"] = "BÜ-Signal der ÖBB",     
        ["BÜ Signale Description"] = "Signale zur Sicherung von Bahnübergängen. Bei blinkendem Licht ist der Bahnübergang technisch gesichert, ansonsten muss der Tfz anhalten und den Bahnübergang manuell sichern.",
        ["links"] = " links",
        ["Type"] = "Typ",
        ["Pfosten"] = "Pfosten",
        ["Bü gelb KM"] = "Bü gelb KM",
        ["Bü weiß KM"] = "Bü weiß KM",
        ["Bü weiß"] = "Bü Bü",
        ["HET"] = "HET",
        ["autom. HET"] = "autom. HET",
        ["ET"] = "ET",
        ["autom. ET"] = "autom. ET",
        ["Wiederholer Pfosten"] = "Wiederholer Pfosten",
        ["Wiederholer Signal"] = "Wiederholer Signal",
        ["P"] = "P",
        ["L"] = "L",
        ["Bü2 alt"] = "Bü2 alt",
        ["Bü2 neu"] = "Bü2 neu",
        ["Bü3"] = "Bü3",
        ["Pfeifpflocḱ"] = "Pfeifpflock (AT)",
        ["TrackPos"] = "Position am Gleis",
        ["right"] = "rechts",
        ["left"] = "links",
        ["MastPos"] = "Position am Mast",
        ["oben"] = "oben",
        ["1 unterhalb"] = "1 unterhalb",
        ["2 unterhalb"] = "2 unterhalb",
        ["Pfosten"] = "Pfosten",
        ["mit L"] = " mit L-Tafel",
        ["mit P"] = " mit P-Tafel",
        ["links"] = " links",
        ["Betonpfosten für BÜ Assets"] = "Betonpfosten für BÜ Assets",
        ["für Assets"] = " (Assets können an diesen Mast nach Wahl hinzugefügt werden)",
        ["Auslöser"] = "\nLöst Pfeifen der vorbeifahrenden Züge aus.",

        ["tooltip_type"] = "Variante",
        ["tooltip_trackpos"] = "Steht das Schild links oder rechts vom Gleis?",
        ["tooltip_mastpos"] = "Wenn mehrere Schilder an einem Mast hängen, können sie hiermit nach unten versetzt werden.",
        ["tooltip_autokm"] = "Bei beschriftbaren Schildern kann eine automatische Nummer generiert werden (sonst manuell als Namen vergeben).",

	}
}
end
